[project]
name = "vkey"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "ipykernel>=6.29.5",
  "pandas>=2.2.3",
  "polars>=1.29.0",
  "pyarrow>=20.0.0",
]
