// This file is auto-generated. Do not edit manually.


pub fn vk_to_cgkeycode(value: Vk) -> Option<CGKeyCode> {
  let result = match value {
    Vk::VolumeMute   => KeyCode::MUTE                      .into(),
    Vk::VolumeDown   => KeyCode::VOLUME_DOWN               .into(),
    Vk::VolumeUp     => KeyCode::VOLUME_UP                 .into(),
    Vk::_0           => KeyCodeExt::kVK_ANSI_0             .into(),
    Vk::_1           => KeyCodeExt::kVK_ANSI_1             .into(),
    Vk::_2           => KeyCodeExt::kVK_ANSI_2             .into(),
    Vk::_3           => KeyCodeExt::kVK_ANSI_3             .into(),
    Vk::_4           => KeyCodeExt::kVK_ANSI_4             .into(),
    Vk::_5           => KeyCodeExt::kVK_ANSI_5             .into(),
    Vk::_6           => KeyCodeExt::kVK_ANSI_6             .into(),
    Vk::_7           => KeyCodeExt::kVK_ANSI_7             .into(),
    Vk::_8           => KeyCodeExt::kVK_ANSI_8             .into(),
    Vk::_9           => KeyCodeExt::kVK_ANSI_9             .into(),
    Vk::A            => KeyCodeExt::kVK_ANSI_A             .into(),
    Vk::B            => KeyCodeExt::kVK_ANSI_B             .into(),
    Vk::C            => KeyCodeExt::kVK_ANSI_C             .into(),
    Vk::CapsLock     => KeyCode::CAPS_LOCK                 .into(),
    Vk::D            => KeyCodeExt::kVK_ANSI_D             .into(),
    Vk::Backspace    => KeyCode::DELETE                    .into(),
    Vk::Delete       => KeyCode::FORWARD_DELETE            .into(),
    Vk::DownArrow    => KeyCode::DOWN_ARROW                .into(),
    Vk::E            => KeyCodeExt::kVK_ANSI_E             .into(),
    Vk::End          => KeyCode::END                       .into(),
    Vk::Escape       => KeyCode::ESCAPE                    .into(),
    Vk::F            => KeyCodeExt::kVK_ANSI_F             .into(),
    Vk::F1           => KeyCode::F1                        .into(),
    Vk::F10          => KeyCode::F10                       .into(),
    Vk::F11          => KeyCode::F11                       .into(),
    Vk::F12          => KeyCode::F12                       .into(),
    Vk::F13          => KeyCode::F13                       .into(),
    Vk::F14          => KeyCode::F14                       .into(),
    Vk::F15          => KeyCode::F15                       .into(),
    Vk::F16          => KeyCode::F16                       .into(),
    Vk::F17          => KeyCode::F17                       .into(),
    Vk::F18          => KeyCode::F18                       .into(),
    Vk::F19          => KeyCode::F19                       .into(),
    Vk::F2           => KeyCode::F2                        .into(),
    Vk::F20          => KeyCode::F20                       .into(),
    Vk::F3           => KeyCode::F3                        .into(),
    Vk::F4           => KeyCode::F4                        .into(),
    Vk::F5           => KeyCode::F5                        .into(),
    Vk::F6           => KeyCode::F6                        .into(),
    Vk::F7           => KeyCode::F7                        .into(),
    Vk::F8           => KeyCode::F8                        .into(),
    Vk::F9           => KeyCode::F9                        .into(),
    Vk::G            => KeyCodeExt::kVK_ANSI_G             .into(),
    Vk::H            => KeyCodeExt::kVK_ANSI_H             .into(),
    Vk::Help         => KeyCode::HELP                      .into(),
    Vk::Home         => KeyCode::HOME                      .into(),
    Vk::I            => KeyCodeExt::kVK_ANSI_I             .into(),
    Vk::J            => KeyCodeExt::kVK_ANSI_J             .into(),
    Vk::K            => KeyCodeExt::kVK_ANSI_K             .into(),
    Vk::L            => KeyCodeExt::kVK_ANSI_L             .into(),
    Vk::Alt          => KeyCode::OPTION                    .into(),
    Vk::LeftArrow    => KeyCode::LEFT_ARROW                .into(),
    Vk::Control      => KeyCode::CONTROL                   .into(),
    Vk::LeftControl  => KeyCode::CONTROL                   .into(),
    Vk::LeftShift    => KeyCode::SHIFT                     .into(),
    Vk::Shift        => KeyCode::SHIFT                     .into(),
    Vk::M            => KeyCodeExt::kVK_ANSI_M             .into(),
    Vk::N            => KeyCodeExt::kVK_ANSI_N             .into(),
    Vk::O            => KeyCodeExt::kVK_ANSI_O             .into(),
    Vk::P            => KeyCodeExt::kVK_ANSI_P             .into(),
    Vk::PageDown     => KeyCode::PAGE_DOWN                 .into(),
    Vk::PageUp       => KeyCode::PAGE_UP                   .into(),
    Vk::Q            => KeyCodeExt::kVK_ANSI_Q             .into(),
    Vk::R            => KeyCodeExt::kVK_ANSI_R             .into(),
    Vk::Enter        => KeyCode::RETURN                    .into(),
    Vk::RightArrow   => KeyCode::RIGHT_ARROW               .into(),
    Vk::RightControl => KeyCode::RIGHT_CONTROL             .into(),
    Vk::RightShift   => KeyCode::RIGHT_SHIFT               .into(),
    Vk::S            => KeyCodeExt::kVK_ANSI_S             .into(),
    Vk::Space        => KeyCode::SPACE                     .into(),
    Vk::T            => KeyCodeExt::kVK_ANSI_T             .into(),
    Vk::Tab          => KeyCode::TAB                       .into(),
    Vk::U            => KeyCodeExt::kVK_ANSI_U             .into(),
    Vk::UpArrow      => KeyCode::UP_ARROW                  .into(),
    Vk::V            => KeyCodeExt::kVK_ANSI_V             .into(),
    Vk::W            => KeyCodeExt::kVK_ANSI_W             .into(),
    Vk::X            => KeyCodeExt::kVK_ANSI_X             .into(),
    Vk::Y            => KeyCodeExt::kVK_ANSI_Y             .into(),
    Vk::Z            => KeyCodeExt::kVK_ANSI_Z             .into(),
    Vk::Numpad0      => KeyCodeExt::kVK_ANSI_Keypad0       .into(),
    Vk::Numpad1      => KeyCodeExt::kVK_ANSI_Keypad1       .into(),
    Vk::Numpad2      => KeyCodeExt::kVK_ANSI_Keypad2       .into(),
    Vk::Numpad3      => KeyCodeExt::kVK_ANSI_Keypad3       .into(),
    Vk::Numpad4      => KeyCodeExt::kVK_ANSI_Keypad4       .into(),
    Vk::Numpad5      => KeyCodeExt::kVK_ANSI_Keypad5       .into(),
    Vk::Numpad6      => KeyCodeExt::kVK_ANSI_Keypad6       .into(),
    Vk::Numpad7      => KeyCodeExt::kVK_ANSI_Keypad7       .into(),
    Vk::Numpad8      => KeyCodeExt::kVK_ANSI_Keypad8       .into(),
    Vk::Numpad9      => KeyCodeExt::kVK_ANSI_Keypad9       .into(),
    Vk::Subtract     => KeyCodeExt::kVK_ANSI_KeypadMinus   .into(),
    Vk::Divide       => KeyCodeExt::kVK_ANSI_KeypadDivide  .into(),
    Vk::Decimal      => KeyCodeExt::kVK_ANSI_KeypadDecimal .into(),
    Vk::Add          => KeyCodeExt::kVK_ANSI_KeypadPlus    .into(),
    Vk::Multiply     => KeyCodeExt::kVK_ANSI_KeypadMultiply.into(),
    _ => return None,
  };
  Some(result)
}

impl crate::convert::Convert<Vk, CGKeyCode> for crate::convert::Converter {
  fn convert(value: Vk) -> Option<CGKeyCode> {
    vk_to_cgkeycode(value)
  }
}
