// This file is auto-generated. Do not edit manually.


pub fn enigo_to_vk(value: Enigo) -> Option<Vk> {
  let result = match value {
    #[cfg(target_os = "windows")]
    Enigo::LButton                      => keys::VK_LBUTTON                        ,
    #[cfg(target_os = "windows")]
    Enigo::RButton                      => keys::VK_RBUTTON                        ,
    #[cfg(target_os = "windows")]
    Enigo::MButton                      => keys::VK_MBUTTON                        ,
    #[cfg(target_os = "windows")]
    Enigo::XButton1                     => keys::VK_XBUTTON1                       ,
    #[cfg(target_os = "windows")]
    Enigo::XButton2                     => keys::VK_XBUTTON2                       ,
    #[cfg(target_os = "windows")]
    Enigo::BrowserBack                  => keys::VK_BROWSER_BACK                   ,
    #[cfg(target_os = "windows")]
    Enigo::BrowserFavorites             => keys::VK_BROWSER_FAVORITES              ,
    #[cfg(target_os = "windows")]
    Enigo::BrowserForward               => keys::VK_BROWSER_FORWARD                ,
    #[cfg(target_os = "windows")]
    Enigo::BrowserHome                  => keys::VK_BROWSER_HOME                   ,
    #[cfg(target_os = "windows")]
    Enigo::BrowserRefresh               => keys::VK_BROWSER_REFRESH                ,
    #[cfg(target_os = "windows")]
    Enigo::BrowserSearch                => keys::VK_BROWSER_SEARCH                 ,
    #[cfg(target_os = "windows")]
    Enigo::BrowserStop                  => keys::VK_BROWSER_STOP                   ,
    #[cfg(target_os = "windows")]
    Enigo::LaunchMail                   => keys::VK_LAUNCH_MAIL                    ,
    #[cfg(target_os = "windows")]
    Enigo::LaunchMediaSelect            => keys::VK_LAUNCH_MEDIA_SELECT            ,
    Enigo::VolumeMute                   => keys::VK_VOLUME_MUTE                    ,
    Enigo::MediaPlayPause               => keys::VK_MEDIA_PLAY_PAUSE               ,
    Enigo::MediaNextTrack               => keys::VK_MEDIA_NEXT_TRACK               ,
    Enigo::MediaPrevTrack               => keys::VK_MEDIA_PREV_TRACK               ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::MediaStop                    => keys::VK_MEDIA_STOP                     ,
    Enigo::VolumeDown                   => keys::VK_VOLUME_DOWN                    ,
    Enigo::VolumeUp                     => keys::VK_VOLUME_UP                      ,
    #[cfg(target_os = "windows")]
    Enigo::Sleep                        => keys::VK_SLEEP                          ,
    #[cfg(target_os = "windows")]
    Enigo::Num0                         => keys::VK_0                              ,
    #[cfg(target_os = "windows")]
    Enigo::Num1                         => keys::VK_1                              ,
    #[cfg(target_os = "windows")]
    Enigo::Num2                         => keys::VK_2                              ,
    #[cfg(target_os = "windows")]
    Enigo::Num3                         => keys::VK_3                              ,
    #[cfg(target_os = "windows")]
    Enigo::Num4                         => keys::VK_4                              ,
    #[cfg(target_os = "windows")]
    Enigo::Num5                         => keys::VK_5                              ,
    #[cfg(target_os = "windows")]
    Enigo::Num6                         => keys::VK_6                              ,
    #[cfg(target_os = "windows")]
    Enigo::Num7                         => keys::VK_7                              ,
    #[cfg(target_os = "windows")]
    Enigo::Num8                         => keys::VK_8                              ,
    #[cfg(target_os = "windows")]
    Enigo::Num9                         => keys::VK_9                              ,
    #[cfg(target_os = "windows")]
    Enigo::A                            => keys::VK_A                              ,
    #[cfg(target_os = "windows")]
    Enigo::Apps                         => keys::VK_APPS                           ,
    #[cfg(target_os = "windows")]
    Enigo::B                            => keys::VK_B                              ,
    #[cfg(target_os = "windows")]
    Enigo::OEM5                         => keys::VK_OEM_5                          ,
    #[cfg(target_os = "windows")]
    Enigo::C                            => keys::VK_C                              ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::Cancel                       => keys::VK_CANCEL                         ,
    Enigo::CapsLock                     => keys::VK_CAPITAL                        ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::Clear                        => keys::VK_CLEAR                          ,
    #[cfg(target_os = "windows")]
    Enigo::OEMComma                     => keys::VK_OEM_COMMA                      ,
    #[cfg(target_os = "windows")]
    Enigo::D                            => keys::VK_D                              ,
    #[cfg(target_os = "windows")]
    Enigo::OEMMinus                     => keys::VK_OEM_MINUS                      ,
    Enigo::Backspace                    => keys::VK_BACK                           ,
    Enigo::Delete                       => keys::VK_DELETE                         ,
    Enigo::DownArrow                    => keys::VK_DOWN                           ,
    #[cfg(target_os = "windows")]
    Enigo::E                            => keys::VK_E                              ,
    Enigo::End                          => keys::VK_END                            ,
    #[cfg(target_os = "windows")]
    Enigo::OEMPlus                      => keys::VK_OEM_PLUS                       ,
    Enigo::Escape                       => keys::VK_ESCAPE                         ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::Execute                      => keys::VK_EXECUTE                        ,
    #[cfg(target_os = "windows")]
    Enigo::F                            => keys::VK_F                              ,
    Enigo::F1                           => keys::VK_F1                             ,
    Enigo::F10                          => keys::VK_F10                            ,
    Enigo::F11                          => keys::VK_F11                            ,
    Enigo::F12                          => keys::VK_F12                            ,
    Enigo::F13                          => keys::VK_F13                            ,
    Enigo::F14                          => keys::VK_F14                            ,
    Enigo::F15                          => keys::VK_F15                            ,
    Enigo::F16                          => keys::VK_F16                            ,
    Enigo::F17                          => keys::VK_F17                            ,
    Enigo::F18                          => keys::VK_F18                            ,
    Enigo::F19                          => keys::VK_F19                            ,
    Enigo::F2                           => keys::VK_F2                             ,
    Enigo::F20                          => keys::VK_F20                            ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::F21                          => keys::VK_F21                            ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::F22                          => keys::VK_F22                            ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::F23                          => keys::VK_F23                            ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::F24                          => keys::VK_F24                            ,
    Enigo::F3                           => keys::VK_F3                             ,
    Enigo::F4                           => keys::VK_F4                             ,
    Enigo::F5                           => keys::VK_F5                             ,
    Enigo::F6                           => keys::VK_F6                             ,
    Enigo::F7                           => keys::VK_F7                             ,
    Enigo::F8                           => keys::VK_F8                             ,
    Enigo::F9                           => keys::VK_F9                             ,
    #[cfg(target_os = "windows")]
    Enigo::OEM2                         => keys::VK_OEM_2                          ,
    #[cfg(target_os = "windows")]
    Enigo::G                            => keys::VK_G                              ,
    #[cfg(target_os = "windows")]
    Enigo::OEM3                         => keys::VK_OEM_3                          ,
    #[cfg(target_os = "windows")]
    Enigo::H                            => keys::VK_H                              ,
    Enigo::Help                         => keys::VK_HELP                           ,
    Enigo::Home                         => keys::VK_HOME                           ,
    #[cfg(target_os = "windows")]
    Enigo::I                            => keys::VK_I                              ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::Insert                       => keys::VK_INSERT                         ,
    #[cfg(target_os = "windows")]
    Enigo::J                            => keys::VK_J                              ,
    #[cfg(target_os = "windows")]
    Enigo::K                            => keys::VK_K                              ,
    #[cfg(target_os = "windows")]
    Enigo::L                            => keys::VK_L                              ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::LMenu                        => keys::VK_LMENU                          ,
    Enigo::Alt                          => keys::VK_MENU                           ,
    Enigo::Option                       => keys::VK_MENU                           ,
    #[cfg(target_os = "windows")]
    Enigo::OEM7                         => keys::VK_OEM_7                          ,
    Enigo::LeftArrow                    => keys::VK_LEFT                           ,
    #[cfg(target_os = "windows")]
    Enigo::OEM4                         => keys::VK_OEM_4                          ,
    Enigo::Control                      => keys::VK_CONTROL                        ,
    Enigo::LControl                     => keys::VK_LCONTROL                       ,
    #[cfg(target_os = "windows")]
    Enigo::LWin                         => keys::VK_LWIN                           ,
    Enigo::Command                      => keys::VK_LWIN                           ,
    Enigo::Meta                         => keys::VK_LWIN                           ,
    Enigo::Super                        => keys::VK_LWIN                           ,
    Enigo::Windows                      => keys::VK_LWIN                           ,
    Enigo::LShift                       => keys::VK_LSHIFT                         ,
    Enigo::Shift                        => keys::VK_SHIFT                          ,
    #[cfg(target_os = "windows")]
    Enigo::M                            => keys::VK_M                              ,
    #[cfg(target_os = "windows")]
    Enigo::N                            => keys::VK_N                              ,
    #[cfg(target_os = "windows")]
    Enigo::OEM102                       => keys::VK_OEM_102                        ,
    #[cfg(target_os = "windows")]
    Enigo::O                            => keys::VK_O                              ,
    #[cfg(target_os = "windows")]
    Enigo::P                            => keys::VK_P                              ,
    Enigo::PageDown                     => keys::VK_NEXT                           ,
    Enigo::PageUp                       => keys::VK_PRIOR                          ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::Pause                        => keys::VK_PAUSE                          ,
    #[cfg(target_os = "windows")]
    Enigo::OEMPeriod                    => keys::VK_OEM_PERIOD                     ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::PrintScr                     => keys::VK_SNAPSHOT                       ,
    #[cfg(target_os = "windows")]
    Enigo::Snapshot                     => keys::VK_SNAPSHOT                       ,
    #[cfg(target_os = "windows")]
    Enigo::Q                            => keys::VK_Q                              ,
    #[cfg(target_os = "windows")]
    Enigo::R                            => keys::VK_R                              ,
    Enigo::Return                       => keys::VK_RETURN                         ,
    #[cfg(target_os = "windows")]
    Enigo::RMenu                        => keys::VK_RMENU                          ,
    Enigo::RightArrow                   => keys::VK_RIGHT                          ,
    #[cfg(target_os = "windows")]
    Enigo::OEM6                         => keys::VK_OEM_6                          ,
    Enigo::RControl                     => keys::VK_RCONTROL                       ,
    #[cfg(target_os = "windows")]
    Enigo::RWin                         => keys::VK_RWIN                           ,
    Enigo::RShift                       => keys::VK_RSHIFT                         ,
    #[cfg(target_os = "windows")]
    Enigo::S                            => keys::VK_S                              ,
    #[cfg(target_os = "windows")]
    Enigo::Scroll                       => keys::VK_SCROLL                         ,
    #[cfg(target_os = "linux")]
    Enigo::ScrollLock                   => keys::VK_SCROLL                         ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::Select                       => keys::VK_SELECT                         ,
    #[cfg(target_os = "windows")]
    Enigo::OEM1                         => keys::VK_OEM_1                          ,
    Enigo::Space                        => keys::VK_SPACE                          ,
    #[cfg(target_os = "windows")]
    Enigo::T                            => keys::VK_T                              ,
    Enigo::Tab                          => keys::VK_TAB                            ,
    #[cfg(target_os = "windows")]
    Enigo::U                            => keys::VK_U                              ,
    Enigo::UpArrow                      => keys::VK_UP                             ,
    #[cfg(target_os = "windows")]
    Enigo::V                            => keys::VK_V                              ,
    #[cfg(target_os = "windows")]
    Enigo::W                            => keys::VK_W                              ,
    #[cfg(target_os = "windows")]
    Enigo::X                            => keys::VK_X                              ,
    #[cfg(target_os = "windows")]
    Enigo::Y                            => keys::VK_Y                              ,
    #[cfg(target_os = "windows")]
    Enigo::Z                            => keys::VK_Z                              ,
    #[cfg(target_os = "windows")]
    Enigo::Numpad0                      => keys::VK_NUMPAD0                        ,
    #[cfg(target_os = "windows")]
    Enigo::Numpad1                      => keys::VK_NUMPAD1                        ,
    #[cfg(target_os = "windows")]
    Enigo::Numpad2                      => keys::VK_NUMPAD2                        ,
    #[cfg(target_os = "windows")]
    Enigo::Numpad3                      => keys::VK_NUMPAD3                        ,
    #[cfg(target_os = "windows")]
    Enigo::Numpad4                      => keys::VK_NUMPAD4                        ,
    #[cfg(target_os = "windows")]
    Enigo::Numpad5                      => keys::VK_NUMPAD5                        ,
    #[cfg(target_os = "windows")]
    Enigo::Numpad6                      => keys::VK_NUMPAD6                        ,
    #[cfg(target_os = "windows")]
    Enigo::Numpad7                      => keys::VK_NUMPAD7                        ,
    #[cfg(target_os = "windows")]
    Enigo::Numpad8                      => keys::VK_NUMPAD8                        ,
    #[cfg(target_os = "windows")]
    Enigo::Numpad9                      => keys::VK_NUMPAD9                        ,
    #[cfg(target_os = "windows")]
    Enigo::Subtract                     => keys::VK_SUBTRACT                       ,
    #[cfg(target_os = "windows")]
    Enigo::Divide                       => keys::VK_DIVIDE                         ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::Numlock                      => keys::VK_NUMLOCK                        ,
    #[cfg(target_os = "windows")]
    Enigo::Decimal                      => keys::VK_DECIMAL                        ,
    #[cfg(target_os = "windows")]
    Enigo::Add                          => keys::VK_ADD                            ,
    #[cfg(target_os = "windows")]
    Enigo::Multiply                     => keys::VK_MULTIPLY                       ,
    #[cfg(target_os = "windows")]
    Enigo::None                         => keys::VK__none_                         ,
    #[cfg(target_os = "windows")]
    Enigo::AbntC1                       => keys::VK_ABNT_C1                        ,
    #[cfg(target_os = "windows")]
    Enigo::AbntC2                       => keys::VK_ABNT_C2                        ,
    #[cfg(target_os = "windows")]
    Enigo::Attn                         => keys::VK_ATTN                           ,
    #[cfg(target_os = "windows")]
    Enigo::Crsel                        => keys::VK_CRSEL                          ,
    #[cfg(target_os = "windows")]
    Enigo::DBEAlphanumeric              => keys::VK_DBE_ALPHANUMERIC               ,
    #[cfg(target_os = "windows")]
    Enigo::DBECodeinput                 => keys::VK_DBE_CODEINPUT                  ,
    #[cfg(target_os = "windows")]
    Enigo::DBESChar                     => keys::VK_DBE_DBCSCHAR                   ,
    #[cfg(target_os = "windows")]
    Enigo::DBEDetermineString           => keys::VK_DBE_DETERMINESTRING            ,
    #[cfg(target_os = "windows")]
    Enigo::DBEEnterDLGConversionMode    => keys::VK_DBE_ENTERDLGCONVERSIONMODE     ,
    #[cfg(target_os = "windows")]
    Enigo::DBEEnterIMEConfigMode        => keys::VK_DBE_ENTERIMECONFIGMODE         ,
    #[cfg(target_os = "windows")]
    Enigo::DBEEnterWordRegisterMode     => keys::VK_DBE_ENTERWORDREGISTERMODE      ,
    #[cfg(target_os = "windows")]
    Enigo::DBEFlushString               => keys::VK_DBE_FLUSHSTRING                ,
    #[cfg(target_os = "windows")]
    Enigo::DBEHiragana                  => keys::VK_DBE_HIRAGANA                   ,
    #[cfg(target_os = "windows")]
    Enigo::DBEKatakana                  => keys::VK_DBE_KATAKANA                   ,
    #[cfg(target_os = "windows")]
    Enigo::DBENoCodepoint               => keys::VK_DBE_NOCODEINPUT                ,
    #[cfg(target_os = "windows")]
    Enigo::DBENoRoman                   => keys::VK_DBE_NOROMAN                    ,
    #[cfg(target_os = "windows")]
    Enigo::DBERoman                     => keys::VK_DBE_ROMAN                      ,
    #[cfg(target_os = "windows")]
    Enigo::DBESBCSChar                  => keys::VK_DBE_SBCSCHAR                   ,
    #[cfg(target_os = "windows")]
    Enigo::Ereof                        => keys::VK_EREOF                          ,
    #[cfg(target_os = "windows")]
    Enigo::Exsel                        => keys::VK_EXSEL                          ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadA                     => keys::VK_GAMEPAD_A                      ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadB                     => keys::VK_GAMEPAD_B                      ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadDPadDown              => keys::VK_GAMEPAD_DPAD_DOWN              ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadDPadLeft              => keys::VK_GAMEPAD_DPAD_LEFT              ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadDPadRight             => keys::VK_GAMEPAD_DPAD_RIGHT             ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadDPadUp                => keys::VK_GAMEPAD_DPAD_UP                ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadLeftShoulder          => keys::VK_GAMEPAD_LEFT_SHOULDER          ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadLeftThumbstickButton  => keys::VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadLeftThumbstickDown    => keys::VK_GAMEPAD_LEFT_THUMBSTICK_DOWN   ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadLeftThumbstickLeft    => keys::VK_GAMEPAD_LEFT_THUMBSTICK_LEFT   ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadLeftThumbstickRight   => keys::VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT  ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadLeftThumbstickUp      => keys::VK_GAMEPAD_LEFT_THUMBSTICK_UP     ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadLeftTrigger           => keys::VK_GAMEPAD_LEFT_TRIGGER           ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadMenu                  => keys::VK_GAMEPAD_MENU                   ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadRightShoulder         => keys::VK_GAMEPAD_RIGHT_SHOULDER         ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadRightThumbstickButton => keys::VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON,
    #[cfg(target_os = "windows")]
    Enigo::GamepadRightThumbstickDown   => keys::VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN  ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadRightThumbstickLeft   => keys::VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT  ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadRightThumbstickRight  => keys::VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadRightThumbstickUp     => keys::VK_GAMEPAD_RIGHT_THUMBSTICK_UP    ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadRightTrigger          => keys::VK_GAMEPAD_RIGHT_TRIGGER          ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadView                  => keys::VK_GAMEPAD_VIEW                   ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadX                     => keys::VK_GAMEPAD_X                      ,
    #[cfg(target_os = "windows")]
    Enigo::GamepadY                     => keys::VK_GAMEPAD_Y                      ,
    #[cfg(target_os = "windows")]
    Enigo::Ico00                        => keys::VK_ICO_00                         ,
    #[cfg(target_os = "windows")]
    Enigo::IcoClear                     => keys::VK_ICO_CLEAR                      ,
    #[cfg(target_os = "windows")]
    Enigo::IcoHelp                      => keys::VK_ICO_HELP                       ,
    #[cfg(target_os = "windows")]
    Enigo::NavigationAccept             => keys::VK_NAVIGATION_ACCEPT              ,
    #[cfg(target_os = "windows")]
    Enigo::NavigationCancel             => keys::VK_NAVIGATION_CANCEL              ,
    #[cfg(target_os = "windows")]
    Enigo::NavigationDown               => keys::VK_NAVIGATION_DOWN                ,
    #[cfg(target_os = "windows")]
    Enigo::NavigationLeft               => keys::VK_NAVIGATION_LEFT                ,
    #[cfg(target_os = "windows")]
    Enigo::NavigationMenu               => keys::VK_NAVIGATION_MENU                ,
    #[cfg(target_os = "windows")]
    Enigo::NavigationRight              => keys::VK_NAVIGATION_RIGHT               ,
    #[cfg(target_os = "windows")]
    Enigo::NavigationUp                 => keys::VK_NAVIGATION_UP                  ,
    #[cfg(target_os = "windows")]
    Enigo::NavigationView               => keys::VK_NAVIGATION_VIEW                ,
    #[cfg(target_os = "windows")]
    Enigo::NoName                       => keys::VK_NONAME                         ,
    #[cfg(target_os = "windows")]
    Enigo::OEM8                         => keys::VK_OEM_8                          ,
    #[cfg(target_os = "windows")]
    Enigo::OEMAttn                      => keys::VK_OEM_ATTN                       ,
    #[cfg(target_os = "windows")]
    Enigo::OEMAuto                      => keys::VK_OEM_AUTO                       ,
    #[cfg(target_os = "windows")]
    Enigo::OEMAx                        => keys::VK_OEM_AX                         ,
    #[cfg(target_os = "windows")]
    Enigo::OEMBacktab                   => keys::VK_OEM_BACKTAB                    ,
    #[cfg(target_os = "windows")]
    Enigo::OEMClear                     => keys::VK_OEM_CLEAR                      ,
    #[cfg(target_os = "windows")]
    Enigo::OEMCopy                      => keys::VK_OEM_COPY                       ,
    #[cfg(target_os = "windows")]
    Enigo::OEMCusel                     => keys::VK_OEM_CUSEL                      ,
    #[cfg(target_os = "windows")]
    Enigo::OEMEnlw                      => keys::VK_OEM_ENLW                       ,
    #[cfg(target_os = "windows")]
    Enigo::OEMFinish                    => keys::VK_OEM_FINISH                     ,
    #[cfg(target_os = "windows")]
    Enigo::OEMFJJisho                   => keys::VK_OEM_FJ_JISHO                   ,
    #[cfg(target_os = "windows")]
    Enigo::OEMFJLoya                    => keys::VK_OEM_FJ_LOYA                    ,
    #[cfg(target_os = "windows")]
    Enigo::OEMFJMasshou                 => keys::VK_OEM_FJ_MASSHOU                 ,
    #[cfg(target_os = "windows")]
    Enigo::OEMFJRoya                    => keys::VK_OEM_FJ_ROYA                    ,
    #[cfg(target_os = "windows")]
    Enigo::OEMFJTouroku                 => keys::VK_OEM_FJ_TOUROKU                 ,
    #[cfg(target_os = "windows")]
    Enigo::OEMJump                      => keys::VK_OEM_JUMP                       ,
    #[cfg(target_os = "windows")]
    Enigo::OEMNECEqual                  => keys::VK_OEM_NEC_EQUAL                  ,
    #[cfg(target_os = "windows")]
    Enigo::OEMPA1                       => keys::VK_OEM_PA1                        ,
    #[cfg(target_os = "windows")]
    Enigo::OEMPA2                       => keys::VK_OEM_PA2                        ,
    #[cfg(target_os = "windows")]
    Enigo::OEMPA3                       => keys::VK_OEM_PA3                        ,
    #[cfg(target_os = "windows")]
    Enigo::OEMReset                     => keys::VK_OEM_RESET                      ,
    #[cfg(target_os = "windows")]
    Enigo::OEMWsctrl                    => keys::VK_OEM_WSCTRL                     ,
    #[cfg(target_os = "windows")]
    Enigo::PA1                          => keys::VK_PA1                            ,
    #[cfg(target_os = "windows")]
    Enigo::Packet                       => keys::VK_PACKET                         ,
    #[cfg(target_os = "windows")]
    Enigo::Play                         => keys::VK_PLAY                           ,
    #[cfg(target_os = "windows")]
    Enigo::Processkey                   => keys::VK_PROCESSKEY                     ,
    #[cfg(target_os = "windows")]
    Enigo::Zoom                         => keys::VK_ZOOM                           ,
    #[cfg(target_os = "windows")]
    Enigo::Accept                       => keys::VK_ACCEPT                         ,
    #[cfg(target_os = "windows")]
    Enigo::Convert                      => keys::VK_CONVERT                        ,
    #[cfg(target_os = "windows")]
    Enigo::Final                        => keys::VK_FINAL                          ,
    #[cfg(target_os = "windows")]
    Enigo::IMEOff                       => keys::VK_IME_OFF                        ,
    #[cfg(target_os = "windows")]
    Enigo::IMEOn                        => keys::VK_IME_ON                         ,
    #[cfg(target_os = "windows")]
    Enigo::Junja                        => keys::VK_JUNJA                          ,
    #[cfg(target_os = "windows")]
    Enigo::Kana                         => keys::VK_KANA                           ,
    #[cfg(target_os = "windows")]
    Enigo::Hangeul                      => keys::VK_HANGEUL                        ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::Hangul                       => keys::VK_HANGUL                         ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::Kanji                        => keys::VK_KANJI                          ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::Hanja                        => keys::VK_HANJA                          ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::ModeChange                   => keys::VK_MODECHANGE                     ,
    #[cfg(target_os = "windows")]
    Enigo::NonConvert                   => keys::VK_NONCONVERT                     ,
    #[cfg(any(target_os = "windows", target_os = "linux"))]
    Enigo::Print                        => keys::VK_PRINT                          ,
    #[cfg(target_os = "windows")]
    Enigo::Separator                    => keys::VK_SEPARATOR                      ,
    #[cfg(target_os = "windows")]
    Enigo::LaunchApp1                   => keys::VK_LAUNCH_APP1                    ,
    #[cfg(target_os = "windows")]
    Enigo::LaunchApp2                   => keys::VK_LAUNCH_APP2                    ,
    _ => return None,
  };
  Some(result)
}

impl crate::convert::Convert<Enigo, Vk> for crate::convert::Converter {
  fn convert(value: Enigo) -> Option<Vk> {
    enigo_to_vk(value)
  }
}
