// This file is auto-generated. Do not edit manually.


pub fn vk_to_keysym(value: Vk) -> Option<Keysym> {
  let result = match value {
    Vk::VolumeMute     => Keysym::XF86_AudioMute       ,
    Vk::MediaPlayPause => Keysym::XF86_AudioPlay       ,
    Vk::NextTrack      => Keysym::XF86_AudioNext       ,
    Vk::PrevTrack      => Keysym::XF86_AudioPrev       ,
    Vk::MediaStop      => Keysym::XF86_AudioStop       ,
    Vk::VolumeDown     => Keysym::XF86_AudioLowerVolume,
    Vk::VolumeUp       => Keysym::XF86_AudioRaiseVolume,
    Vk::_0             => Keysym::_0                   ,
    Vk::_1             => Keysym::_1                   ,
    Vk::_2             => Keysym::_2                   ,
    Vk::_3             => Keysym::_3                   ,
    Vk::_4             => Keysym::_4                   ,
    Vk::_5             => Keysym::_5                   ,
    Vk::_6             => Keysym::_6                   ,
    Vk::_7             => Keysym::_7                   ,
    Vk::_8             => Keysym::_8                   ,
    Vk::_9             => Keysym::_9                   ,
    Vk::A              => Keysym::A                    ,
    Vk::B              => Keysym::B                    ,
    Vk::C              => Keysym::C                    ,
    Vk::Cancel         => Keysym::Cancel               ,
    Vk::CapsLock       => Keysym::Caps_Lock            ,
    Vk::Clear          => Keysym::Clear                ,
    Vk::D              => Keysym::D                    ,
    Vk::Backspace      => Keysym::BackSpace            ,
    Vk::Delete         => Keysym::Delete               ,
    Vk::DownArrow      => Keysym::Down                 ,
    Vk::E              => Keysym::E                    ,
    Vk::End            => Keysym::End                  ,
    Vk::Escape         => Keysym::Escape               ,
    Vk::Execute        => Keysym::Execute              ,
    Vk::F              => Keysym::F                    ,
    Vk::F1             => Keysym::F1                   ,
    Vk::F10            => Keysym::F10                  ,
    Vk::F11            => Keysym::F11                  ,
    Vk::F12            => Keysym::F12                  ,
    Vk::F13            => Keysym::F13                  ,
    Vk::F14            => Keysym::F14                  ,
    Vk::F15            => Keysym::F15                  ,
    Vk::F16            => Keysym::F16                  ,
    Vk::F17            => Keysym::F17                  ,
    Vk::F18            => Keysym::F18                  ,
    Vk::F19            => Keysym::F19                  ,
    Vk::F2             => Keysym::F2                   ,
    Vk::F20            => Keysym::F20                  ,
    Vk::F21            => Keysym::F21                  ,
    Vk::F22            => Keysym::F22                  ,
    Vk::F23            => Keysym::F23                  ,
    Vk::F24            => Keysym::F24                  ,
    Vk::F3             => Keysym::F3                   ,
    Vk::F4             => Keysym::F4                   ,
    Vk::F5             => Keysym::F5                   ,
    Vk::F6             => Keysym::F6                   ,
    Vk::F7             => Keysym::F7                   ,
    Vk::F8             => Keysym::F8                   ,
    Vk::F9             => Keysym::F9                   ,
    Vk::G              => Keysym::G                    ,
    Vk::H              => Keysym::H                    ,
    Vk::Help           => Keysym::Help                 ,
    Vk::Home           => Keysym::Home                 ,
    Vk::I              => Keysym::I                    ,
    Vk::Insert         => Keysym::Insert               ,
    Vk::J              => Keysym::J                    ,
    Vk::K              => Keysym::K                    ,
    Vk::L              => Keysym::L                    ,
    Vk::LeftMenu       => Keysym::Menu                 ,
    Vk::Alt            => Keysym::Alt_L                ,
    Vk::LeftArrow      => Keysym::Left                 ,
    Vk::Control        => Keysym::Control_L            ,
    Vk::LeftControl    => Keysym::Control_L            ,
    Vk::LeftWin        => Keysym::Super_L              ,
    Vk::LeftShift      => Keysym::Shift_L              ,
    Vk::Shift          => Keysym::Shift_L              ,
    Vk::M              => Keysym::M                    ,
    Vk::N              => Keysym::N                    ,
    Vk::O              => Keysym::O                    ,
    Vk::P              => Keysym::P                    ,
    Vk::PageDown       => Keysym::Page_Down            ,
    Vk::PageUp         => Keysym::Page_Up              ,
    Vk::Pause          => Keysym::Pause                ,
    Vk::PrintScreen    => Keysym::Print                ,
    Vk::Q              => Keysym::Q                    ,
    Vk::R              => Keysym::R                    ,
    Vk::Enter          => Keysym::Return               ,
    Vk::RightMenu      => Keysym::Alt_R                ,
    Vk::RightArrow     => Keysym::Right                ,
    Vk::RightControl   => Keysym::Control_R            ,
    Vk::RightWin       => Keysym::Super_R              ,
    Vk::RightShift     => Keysym::Shift_R              ,
    Vk::S              => Keysym::S                    ,
    Vk::Scroll         => Keysym::Scroll_Lock          ,
    Vk::Select         => Keysym::Select               ,
    Vk::Space          => Keysym::space                ,
    Vk::T              => Keysym::T                    ,
    Vk::Tab            => Keysym::Tab                  ,
    Vk::U              => Keysym::U                    ,
    Vk::UpArrow        => Keysym::Up                   ,
    Vk::V              => Keysym::V                    ,
    Vk::W              => Keysym::W                    ,
    Vk::X              => Keysym::X                    ,
    Vk::Y              => Keysym::Y                    ,
    Vk::Z              => Keysym::Z                    ,
    Vk::Numpad0        => Keysym::KP_0                 ,
    Vk::Numpad1        => Keysym::KP_1                 ,
    Vk::Numpad2        => Keysym::KP_2                 ,
    Vk::Numpad3        => Keysym::KP_3                 ,
    Vk::Numpad4        => Keysym::KP_4                 ,
    Vk::Numpad5        => Keysym::KP_5                 ,
    Vk::Numpad6        => Keysym::KP_6                 ,
    Vk::Numpad7        => Keysym::KP_7                 ,
    Vk::Numpad8        => Keysym::KP_8                 ,
    Vk::Numpad9        => Keysym::KP_9                 ,
    Vk::Subtract       => Keysym::KP_Subtract          ,
    Vk::Divide         => Keysym::KP_Divide            ,
    Vk::Numlock        => Keysym::Num_Lock             ,
    Vk::Decimal        => Keysym::KP_Decimal           ,
    Vk::Add            => Keysym::KP_Add               ,
    Vk::Multiply       => Keysym::KP_Multiply          ,
    Vk::Kanji          => Keysym::Kanji                ,
    Vk::ModeChange     => Keysym::Mode_switch          ,
    Vk::Print          => Keysym::Print                ,
    _ => return None,
  };
  Some(result)
}

impl crate::convert::Convert<Vk, Keysym> for crate::convert::Converter {
  fn convert(value: Vk) -> Option<Keysym> {
    vk_to_keysym(value)
  }
}
