name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        features: [ "", "--no-default-features", "--all-features" ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose ${{ matrix.features }}
    - name: Run tests
      run: cargo test --verbose ${{ matrix.features }}
